version: '3.9'

services:
  mongodb:
    image: bitnami/mongodb:4.2.3-debian-10-r31
    restart: always
    user: root
    environment:
      - MONGODB_DATABASE=bf
      - MONGODB_DISABLE_SYSTEM_LOG=no
      - MONGODB_ENABLE_DIRECTORY_PER_DB=no
      - MONGODB_ENABLE_IPV6=no
      - MONGODB_PASSWORD=SheeF2faidaen2
      - MONGODB_ROOT_PASSWORD=vahS1Eeyocha0cho
      - MONGODB_SYSTEM_LOG_VERBOSITY=2
      - MONGODB_USERNAME=botfront
    volumes:
      - ./mongodb:/bitnami/mongodb/
    ports:
      - 27117:27017

  rasa:
    image: ghcr.io/epoch8/rasa-for-botfront/rasa:2.3.3-e8-1.2.0
    restart: always
    user: root
    environment:
      BF_PROJECT_ID: LxfpscXvZ5LADGhuc
      BOTFRONT_ENV: development
      BF_URL: http://172.17.0.1:3000/graphql
    volumes:
      - rasa_models:/app/models
    ports:
      - 5005:5005
    entrypoint:
      - rasa
      - run
      - --enable-api
      - --response-timeout
      - '43200'
      - --debug

  actions:
    image: ghcr.io/epoch8/chatbot-saas/rasa-actions:0.1.0
    restart: always
    ports:
      - 5055:5055
    entrypoint:
      - rasa
      - run
      - actions
      - --debug



volumes:
  rasa_models: